#!/usr/bin/env bash
# Write apps/*/.env.local from env.local (or env.local.example).
# Shared keys go into every app. App URL blocks keep the right localhost ports.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/env.local"
if [[ ! -f "$SRC" ]]; then
  SRC="$ROOT/env.local.example"
fi

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

extract_block() {
  local app="$1"
  awk -v app="$app" '
    $0 == "# ===== BEGIN apps/" app " =====" {p=1; next}
    $0 == "# ===== END apps/" app " =====" {p=0}
    p && $0 !~ /^[[:space:]]*#/ && $0 ~ /=/
  ' "$SRC"
}

shared_keys() {
  awk '
    /^# ===== BEGIN / {exit}
    /^[[:space:]]*#/ {next}
    /^[[:space:]]*$/ {next}
    /=/ {print}
  ' "$SRC"
}

write_app() {
  local rel="$1"
  local dest="$ROOT/apps/$rel/.env.local"
  if [[ -f "$dest" && "$FORCE" -ne 1 ]]; then
    echo "skip $rel (exists — pass --force to overwrite)"
    return
  fi
  {
    echo "# Generated by scripts/install-local-env.sh from ${SRC##*/}"
    echo "# Do not commit this file."
    echo
    shared_keys
    echo
    extract_block "$rel"
  } > "$dest"
  echo "wrote $rel"
}

for app in web web_v2 ios admin free-ios; do
  [[ -d "$ROOT/apps/$app" ]] || continue
  write_app "$app"
done

echo "Done. Source: ${SRC##*/}"
echo "Fill secrets in env.local (copy of env.local.example), then re-run with --force if needed."
