/** public.accounts.traits — account_trait enum values. */
export const ACCOUNT_TRAIT_VALUES = [
  'sentimental',
  'nostalgic',
  'reflective',
  'introspective',
  'peace-seeking',
  'hopeful',
  'healing',
  'grateful',
  'steward',
  'protector',
  'guardian',
  'caretaker',
  'sustainability-minded',
  'prepared',
  'duty-driven',
  'explorer',
  'curious',
  'wanderer',
  'adventurous',
  'experimental',
  'traveler',
  'localist',
  'rooted',
  'neighborhood-focused',
  'hometown-proud',
  'belonging-driven',
  'place-attached',
  'connector',
  'relationship-builder',
  'organizer',
  'gatherer',
  'helper',
  'supportive',
  'communicative',
  'storyteller',
  'writer',
  'expressive',
  'documentarian',
  'artistic',
  'poetic',
  'observer',
  'pattern-seeker',
  'analytical',
  'detail-oriented',
  'context-aware',
  'systems-thinking',
  'keeper-of-memory',
  'historian',
  'archivist',
  'tradition-oriented',
  'legacy-minded',
  'remembrance-focused',
  'urban-focused',
  'city-oriented',
  'infrastructure-aware',
  'development-curious',
  'pedestrian-minded',
  'rural-rooted',
  'land-connected',
  'nature-centered',
  'outdoor-oriented',
  'solitude-seeking',
  'problem-solver',
  'fixer',
  'navigator',
  'watchful',
  'safety-focused',
  'quiet-participant',
  'conversational',
  'selective',
  'repeat-visitor',
  'saver',
  'reactor',
  'slow-paced',
  'high-energy',
  'optimistic',
  'contemplative',
  'emotionally-fluid',
  'seasonally-adaptive',
  'business-owner',
  'local-shop-owner',
  'hospitality-operator',
  'property-owner',
  'side-hustler',
  'service-provider',
  'tradesperson',
  'builder',
  'technician',
  'creative-worker',
  'educator',
  'care-worker',
  'food-worker',
  'remote-worker',
  'mobile-worker',
  'gig-contract-worker',
  'student-worker',
  'retired-semi-retired',
  'knowledge-based',
  'hands-on',
  'creative-driven',
  'product-based',
  'relationship-based',
  'process-driven',
  'advisory-focused',
  'local-consumer',
  'buy-local-advocate',
  'circular-economy-minded',
  'budget-conscious',
  'experience-driven',
  'impact-driven',
  'formal-business',
  'micro-commerce',
  'peer-to-peer',
  'event-based',
  'pop-up-temporary',
  'digital-only',
  'economy-observant',
  'trend-aware',
  'place-value-oriented',
] as const;

export type AccountTrait = (typeof ACCOUNT_TRAIT_VALUES)[number];

export const MAX_ACCOUNT_TRAITS = 5;

const TRAIT_EMOJI: Record<AccountTrait, string> = {
  sentimental: '🥹',
  nostalgic: '🕰️',
  reflective: '🪞',
  introspective: '🧘',
  'peace-seeking': '☮️',
  hopeful: '🌅',
  healing: '🌿',
  grateful: '🙏',
  steward: '🧭',
  protector: '🛡️',
  guardian: '🦁',
  caretaker: '💚',
  'sustainability-minded': '♻️',
  prepared: '🧰',
  'duty-driven': '🎖️',
  explorer: '🧭',
  curious: '🔎',
  wanderer: '🥾',
  adventurous: '⛰️',
  experimental: '🧪',
  traveler: '✈️',
  localist: '📍',
  rooted: '🌳',
  'neighborhood-focused': '🏘️',
  'hometown-proud': '❤️',
  'belonging-driven': '🤝',
  'place-attached': '🏡',
  connector: '🔗',
  'relationship-builder': '🫂',
  organizer: '📋',
  gatherer: '🧺',
  helper: '🙋',
  supportive: '🫶',
  communicative: '💬',
  storyteller: '📖',
  writer: '✍️',
  expressive: '🎭',
  documentarian: '🎞️',
  artistic: '🎨',
  poetic: '🪶',
  observer: '👀',
  'pattern-seeker': '🧩',
  analytical: '📊',
  'detail-oriented': '🔬',
  'context-aware': '🗺️',
  'systems-thinking': '⚙️',
  'keeper-of-memory': '🧵',
  historian: '📜',
  archivist: '🗃️',
  'tradition-oriented': '🏺',
  'legacy-minded': '🕯️',
  'remembrance-focused': '💐',
  'urban-focused': '🏙️',
  'city-oriented': '🚇',
  'infrastructure-aware': '🏗️',
  'development-curious': '🧱',
  'pedestrian-minded': '🚶',
  'rural-rooted': '🌾',
  'land-connected': '🏞️',
  'nature-centered': '🌲',
  'outdoor-oriented': '🏕️',
  'solitude-seeking': '🌫️',
  'problem-solver': '💡',
  fixer: '🔧',
  navigator: '🧭',
  watchful: '🦅',
  'safety-focused': '🚨',
  'quiet-participant': '🤫',
  conversational: '🗣️',
  selective: '🎯',
  'repeat-visitor': '🔁',
  saver: '💾',
  reactor: '⚡',
  'slow-paced': '🐢',
  'high-energy': '🔥',
  optimistic: '☀️',
  contemplative: '☁️',
  'emotionally-fluid': '🌊',
  'seasonally-adaptive': '🍂',
  'business-owner': '🏪',
  'local-shop-owner': '🛒',
  'hospitality-operator': '🍽️',
  'property-owner': '🔑',
  'side-hustler': '💼',
  'service-provider': '🛎️',
  tradesperson: '🛠️',
  builder: '👷',
  technician: '🪛',
  'creative-worker': '🖌️',
  educator: '📚',
  'care-worker': '🩺',
  'food-worker': '👨‍🍳',
  'remote-worker': '💻',
  'mobile-worker': '🚐',
  'gig-contract-worker': '📅',
  'student-worker': '🎓',
  'retired-semi-retired': '🏖️',
  'knowledge-based': '🧠',
  'hands-on': '🙌',
  'creative-driven': '✨',
  'product-based': '📦',
  'relationship-based': '💞',
  'process-driven': '📈',
  'advisory-focused': '📎',
  'local-consumer': '🛍️',
  'buy-local-advocate': '🏪',
  'circular-economy-minded': '🔄',
  'budget-conscious': '💵',
  'experience-driven': '🎢',
  'impact-driven': '🌍',
  'formal-business': '🏢',
  'micro-commerce': '🧃',
  'peer-to-peer': '↔️',
  'event-based': '🎟️',
  'pop-up-temporary': '⛺',
  'digital-only': '📱',
  'economy-observant': '📉',
  'trend-aware': '📡',
  'place-value-oriented': '💎',
};

export function formatTraitLabel(trait: string): string {
  return trait
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export function formatTraitEmoji(trait: string): string {
  return TRAIT_EMOJI[trait as AccountTrait] ?? '✨';
}
